### ISSUE TITLE
Averiguar content mixed, no depender, pronto sera restringido

### ISSUE THREAD

**Issue by OscarDevCPP** [puyu-pe/puka-http#9]
* [Detalles sobre el contenido mixto](https://www.electronjs.org/docs/latest/tutorial/security#8-do-not-enable-allowrunninginsecurecontent)
* [Blog del 28 de mayo de 2021, los navegadores no permite conexiones ws no seguras desde sitios web seguros (https)](https://www.damirscorner.com/blog/posts/20210528-AllowingInsecureWebsocketConnections.html)
* [Post en stack-overflow, no se puede https con ws, proponen servidores proxis pero no es la mejor forma. ](https://stackoverflow.com/questions/51201086/how-to-redirect-https-to-insecure-ws)

**Comment by velnae** [comment]
- documentar o poner enlaces de informacion que indica content mixed sera bloqueado mas adelante

- hacer pruebas simples de websocket 
https -> websocket local
http -> websocket local

**Comment by velnae** [comment]
investigar y agregar recursos url de crhome donde indica fechas donde descontinua el soporte para contente mixed

**Comment by OscarDevCPP** [comment]
* En el siguiente [enlace](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins) se menciona que la compatibilidad con http no desaparecera en un futuro previsible.
* En otro [enlace](https://web.dev/articles/how-to-use-local-https?hl=es), proponen una serie de soluciones como el certificado local utilizando mkcert

**Comment by OscarDevCPP** [comment]
* otra solucion propuesta por phind es que se configure un proxi inverso usando ngnix , esto es valido? desconosco varias cosas de ngnix y un proxi inverso

**Comment by OscarDevCPP** [comment]
* La solución de utilizar mkcert parece interesante, ya que javalin (el framework http de java) permite configurar un certificado, entonces se le podria agregar a puka la posibilidad de pasarle un certificado y podria funcionar, Considerar esto en futuro

**Comment by OscarDevCPP** [comment]
* No se pudo encontrar con exactitud si algun dia el flag "#unsafely-treat-insecure-origin-as-secure", desaparesca, pero lo que si esta claro, es que no es la mejor forma de trabajar, asi que se debe intentar otro tipo de soluciones
